### ISSUE TITLE
GVFS is also GNOME Virtual File System

### ISSUE THREAD

**Issue by lmcarreiro** [Microsoft/GVFS#31] opened 2017-05-25 20:07 UTC
Wouldn't be better to call this as GitVFS to avoid confusion?

**Comment by sanoursa** [comment] 2017-05-25 20:19
This is a dupe of #7. Really, any combination with VFS is problematic because it's such a generic acronym and already heavily used, but it's something we're thinking about.

**Closed by sanoursa** 2017-05-25 20:19 UTC
