### ISSUE TITLE
the name gvfs is already used by another product

### ISSUE THREAD

**Issue by BenoitHd** [Microsoft/GVFS#21] opened 2017-02-22 09:26 UTC
Hi

This project use a name that is already in use for "Virtual filesystem implementation for GIO"
I suppose that it is an error of assessment and that she will be corrected.

Url of the project https://git.gnome.org/browse/gvfs/

Thank you

**Comment by sanoursa** [comment] 2017-02-22 15:47
This is a dupe of #7

**Closed by sanoursa** 2017-02-22 15:47 UTC
